spring:
  data:
    mongodb:
     uri: ${MONGODB_URI:mongodb://localhost:27017/?authSource=admin}

http:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:8080

mongock:
  migration-scan-package: br.com.specvora_service.vehicle.migration

firebase:
  credentials:
   path: ${FIREBASE_CREDENTIALS_PATH:/path/to/firebase-key.json}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

security:
  jwt:
    secret: ${JWT_SECRET:specvora-devsecops-super-secret-jwt-key-for-fiap-2026}
    expiration-hours: ${JWT_EXPIRATION_HOURS:2}